### ISSUE TITLE
Connecting to owncloud over https (self signed) fails with "SSL recoverable exception"

### ISSUE THREAD

**Issue by mendhak** [owncloud/android-library#106]
I am attempting to connect to an owncloud server where the user has issued a self signed certificate.

I try to connect like so, and I am using the [SelfSignedConfidentSslSocketFactory](https://github.com/owncloud/android-library/blob/master/test_client/src/com/owncloud/android/lib/test_project/SelfSignedConfidentSslSocketFactory.java), so that any self signed certificate can be accepted.  I got this initial code from the [test app](https://github.com/owncloud/android-library/blob/5985ba9a9fd9a208b2a09ee7809949874e0c3a97/test_client/tests/src/com/owncloud/android/lib/test_project/test/SimpleFactoryManagerTest.java).

```
  Protocol pr = Protocol.getProtocol("https");
 if (pr == null || !(pr.getSocketFactory() instanceof SelfSignedConfidentSslSocketFactory)) {
     try {
         ProtocolSocketFactory psf = new SelfSignedConfidentSslSocketFactory();
         Protocol.registerProtocol( "https", new Protocol("https", psf, 443));

     } catch (GeneralSecurityException e) {
         tracer.error("Self-signed confident SSL context could not be loaded", e);
     }
 }

 OwnCloudClient client = OwnCloudClientFactory.createOwnCloudClient(Uri.parse(servername), AppSettings.getInstance(), true);
 client.setDefaultTimeouts('\uea60', '\uea60');
 client.setFollowRedirects(true);
 client.setCredentials(
         OwnCloudCredentialsFactory.newBasicCredentials(username, password)
 );

 String remotePath = directory + FileUtils.PATH_SEPARATOR + localFile.getName();
 String mimeType = "application/octet-stream"; //unused
 UploadRemoteFileOperation uploadOperation = new UploadRemoteFileOperation(localFile.getAbsolutePath(), remotePath, mimeType);
 uploadOperation.execute(client,this);
```

This attempts to connect and fails with

```
  01-30 00:23:28.774     948-2093/com.mendhak.gpslogger E/OwnCloudJob﹕ onRemoteOperationFinish:100 - SSL recoverable exception
      com.owncloud.android.lib.common.network.CertificateCombinedException: null
              at com.owncloud.android.lib.common.network.AdvancedX509TrustManager.checkServerTrusted(AdvancedX509TrustManager.java:105) ~[na:0.0]
              at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:116) ~[na:0.0]
              at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:550) ~[na:0.0]
              at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method) ~[na:0.0]
              at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:318) ~[na:0.0]
              at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.verifyPeerIdentity(AdvancedSslSocketFactory.java:248) ~[na:0.0]
              at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:185) ~[na:0.0]
              at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707) ~[na:0.0]
              at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361) ~[na:0.0]
              at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387) ~[na:0.0]
              at org.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171) ~[na:0.0]
              at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397) ~[na:0.0]
              at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323) ~[na:0.0]
              at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:223) ~[na:0.0]
              at com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.uploadFile(UploadRemoteFileOperation.java:120) ~[na:0.0]
              at com.owncloud.android.lib.resources.files.UploadRemoteFileOperation.run(UploadRemoteFileOperation.java:88) ~[na:0.0]
              at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:331) ~[na:0.0]
              at java.lang.Thread.run(Thread.java:818) ~[na:0.0]
```

Is there something else I should be doing to trust self signed certs?

**Comment by davivel** [comment]
Hi, @mendhak . Sorry for answering so absurdly late.

This is a tricky question.

First, you shouldn't use ```SelfSignedConfidentSslSocketFactory```. It's unsafe for real apps, since it's basically creating a security hole.

In any case, if you want to use it, then you shouldn't get your ```OwncloudClient``` with ```OwnCloudClientFactory``` , since it's registering the safe ```AdvancedSslSocketFactory``` , overriding the register you made before of your ```SelfSignedConfidentSslSocketFactory``` . You will need to follow the same steps in the test you linked before, in the method ```setUp()```, to get a client from ```SimpleFactoryManager.getClientFor(,)```

*** 

The safe option requires more work. You need to catch any ```CertificateCombinedException``` and show a dialog warning the user about the problems with the server. If the user still wants to trust the certificate, then you need to safe it in the private trust store handled by ```NetworkUtils```.  You can see how we do it in the ownCloud app here: https://github.com/owncloud/android/blob/master/src/com/owncloud/android/ui/dialog/SslUntrustedCertDialog.java

**Comment by mendhak** [comment]
And sorry for my late reply reply - thanks for that reference, I'll follow it, looks like a pretty good way to do it (prompt user and add to keystore)

Thanks!  I'll close this one.

**Comment by mendhak** [comment]
@davivel and @masensio - just wanted to thank you again.  I followed your implementation and understood it, it was a very educational experience with regards to trust managers and hostname verification.  A lot of implementations on the interweb simpy bypass everything and I had fallen for the easy way out but this showed me how important security is.  Really great job.

**Comment by davivel** [comment]
@mendhak , thank you very much for your words. It's always a pleasure talk to you, I'd just like to have more time available for it.
