### ISSUE TITLE
SSL recoverable exception

### ISSUE THREAD

**Issue by androGG** [owncloud/android-library#190]
Hello,
i have installed owncloud server version 10, then i imported a wildcard certificate which is from comodo (*.domain.com). When I connect to the cloud via a browser the certicate works perfect. 
When i try to connect with the android-library i get the following exception:
```
E/ReadRemoteFolderOperation: Synchronized /: SSL recoverable exception
                                                                             com.owncloud.android.lib.common.network.CertificateCombinedException
at com.owncloud.android.lib.common.network.AdvancedX509TrustManager.checkServerTrusted(AdvancedX509TrustManager.java:105)
                                                                                 at com.android.org.conscrypt.Platform.checkServerTrusted(Platform.java:117)
                                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:556)
                                                                                 at com.android.org.conscrypt.NativeCrypto.SSL_do_handshake(Native Method)
                                                                                 at com.android.org.conscrypt.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:324)
                                                                                 at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.verifyPeerIdentity(AdvancedSslSocketFactory.java:247)
                                                                                 at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:183)
                                                                                 at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)
                                                                                 at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)
```

is there anybody who can help me with this problem?
Thanks!!

**Comment by JuancaG05** [comment]
Outdated, closing here 🚀
