### ISSUE TITLE
Have problem to connect to OwnCloud server with android api version under 19

### ISSUE THREAD

**Issue by masoodbayati** [owncloud/android-library#87]
When i want to connect to the server with  android api version under 19 i get this runtime exception but with  api version upper than 19 it works correctly.

com.owncloud.android.lib.sampleclient E/com.owncloud.android.lib.sampleclient.MainActivity﹕ SSL recoverable exception
com.owncloud.android.lib.common.network.CertificateCombinedException
at com.owncloud.android.lib.common.network.AdvancedX509TrustManager.checkServerTrusted(AdvancedX509TrustManager.java:105)
at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.verifyCertificateChain(OpenSSLSocketImpl.java:597)
at org.apache.harmony.xnet.provider.jsse.NativeCrypto.SSL_do_handshake(Native Method)         at org.apache.harmony.xnet.provider.jsse.OpenSSLSocketImpl.startHandshake(OpenSSLSocketImpl.java:398)          at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.verifyPeerIdentity(AdvancedSslSocketFactory.java:248)         at com.owncloud.android.lib.common.network.AdvancedSslSocketFactory.createSocket(AdvancedSslSocketFactory.java:185)
at org.apache.commons.httpclient.HttpConnection.open(HttpConnection.java:707)         at org.apache.commons.httpclient.MultiThreadedHttpConnectionManager$HttpConnectionAdapter.open(MultiThreadedHttpConnectionManager.java:1361)         at org.apache.commons.httpclient.HttpMethodDirector.executeWithRetry(HttpMethodDirector.java:387         atorg.apache.commons.httpclient.HttpMethodDirector.executeMethod(HttpMethodDirector.java:171)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:397)
at org.apache.commons.httpclient.HttpClient.executeMethod(HttpClient.java:323)            at com.owncloud.android.lib.common.OwnCloudClient.executeMethod(OwnCloudClient.java:222)        at com.owncloud.android.lib.resources.files.ReadRemoteFolderOperation.run(ReadRemoteFolderOperation.java:79)
 at com.owncloud.android.lib.common.operations.RemoteOperation.run(RemoteOperation.java:303)

**Comment by davivel** [comment]
Ho, @kahkeshan2 . Sorry for answering so late. 

Is this still a problem for you?

Are you testing in the same device both times, or in devices with different Android versions? What are those versions?

Are you using a self-signed certificate in your ownCloud server?

**Comment by GurpreetSK95** [comment]
Is the problem solved yet?

**Comment by abelgardep** [comment]
Android Api19 is not supported anymore, so we can close this now
