### ISSUE TITLE
`java.lang.SecurityException: caller uid xxxxx is different than the authenticator's uid` when calling OwnCloudClientFactory.createOwnCloudClient

### ISSUE THREAD

**Issue by kh0r** [owncloud/android-library#99]
My app displays a list of owncloud accounts retrieved with  `AccountManager.get(this).getAccountsByType("owncloud")`

After the user selects an account I try to create an OwnCloudClient with `OwnCloudClientFactory.createOwnCloudClient(selectedAccount, MainActivity.this);`.

But the application crashes with a runtime exception: 
```
Caused by: java.lang.SecurityException: caller uid 10341 is different than the authenticator's uid
   at android.os.Parcel.readException(Parcel.java:1546)
   at android.os.Parcel.readException(Parcel.java:1499)
   at android.accounts.IAccountManager$Stub$Proxy.getUserData(IAccountManager.java:692)
   at android.accounts.AccountManager.getUserData(AccountManager.java:344)
   at com.owncloud.android.lib.common.accounts.AccountUtils.getBaseUrlForAccount(AccountUtils.java:141)
   at com.owncloud.android.lib.common.OwnCloudClientFactory.createOwnCloudClient(OwnCloudClientFactory.java:77)
...
```

**Comment by davivel** [comment]
Hi, @kh0r . Sorry for answering so late.

That problem is due to security constrains in the Android framework. Your app cannot access accounts created by other apps. 

For Android versions up to API level 22 you can try to request the permission MANAGE_ACCOUNTS in your AndroidManifest.xml file, but I'm not sure that will allow you to read all the values stored in the account.

The library is not conceived to get your app shares accounts with the ownCloud app. You should use your own account type (not "owncloud"), and your app should create and manage the accounts it needs separately of the ownCloud app.
